"use client";
import { useEffect, useMemo, useState } from "react";
function fmt(v){return Number(v||0).toLocaleString("en-US")}
function linePoints(values,w=900,h=300,p=30){if(!values.length)return "";const min=Math.min(...values),max=Math.max(...values),span=max-min||1;return values.map((v,i)=>`${(p+i/Math.max(values.length-1,1)*(w-p*2)).toFixed(1)},${(h-p-((v-min)/span)*(h-p*2)).toFixed(1)}`).join(" ")}
export default function PositioningClient(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/positioning',{cache:'no-store'}).then(r=>r.json()).then(setData).catch(()=>setData({data:[]})).finally(()=>setLoading(false))},[]);
 const rows=data?.data||[]; const latest=rows.at(-1); const prev=rows.at(-2); const netChange=latest&&prev?latest.nonCommercialNet-prev.nonCommercialNet:null;
 const chart=useMemo(()=>rows.map(x=>x.nonCommercialNet),[rows]);
 return <main className="positioning-page"><section className="analytics-hero positioning-hero"><div className="analytics-hero-grid"/><div className="analytics-hero-inner"><span className="section-kicker light">POSITIONING & COT / STEP 5</span><h1>Market Positioning</h1><p>Weekly futures positioning context for gold, built from the CFTC Legacy Futures Only report. Track speculative net exposure and changes in positioning over time.</p></div></section><section className="analytics-body">
  <div className="positioning-overview"><article><span>NON-COMMERCIAL NET</span><strong>{loading?'…':latest?fmt(latest.nonCommercialNet):'Unavailable'}</strong><small>{netChange!=null?`${netChange>=0?'+':''}${fmt(netChange)} vs prior report`:latest?.date||'—'}</small></article><article><span>OPEN INTEREST</span><strong>{loading?'…':latest?fmt(latest.openInterest):'Unavailable'}</strong><small>Latest report</small></article><article><span>COMMERCIAL NET</span><strong>{loading?'…':latest?fmt(latest.commercialNet):'Unavailable'}</strong><small>Hedging-side net position</small></article></div>
  <div className="chart-panel"><div className="chart-panel-head"><div><span className="section-kicker">SPECULATIVE POSITIONING</span><h2>Non-commercial net exposure</h2><p>Contracts · weekly CFTC report</p></div></div><div className="chart-wrap">{rows.length?<svg viewBox="0 0 900 300" role="img" aria-label="Gold non-commercial net positioning chart"><line x1="30" y1="150" x2="870" y2="150" className="chart-axis"/><polyline points={linePoints(chart)} fill="none" className="chart-line"/></svg>:<div className="chart-empty">{loading?'Loading CFTC positioning data…':'CFTC positioning feed is temporarily unavailable.'}</div>}</div><div className="chart-footer"><span>Source: CFTC Legacy — Futures Only</span><span>Reports shown: {rows.length}</span></div></div>
  <div className="cot-table-wrap"><div className="table-head"><div><span className="section-kicker">REPORT HISTORY</span><h2>Latest Gold positioning</h2></div></div><div className="cot-table"><div className="cot-row cot-head"><span>Report date</span><span>Non-commercial long</span><span>Non-commercial short</span><span>Net</span></div>{rows.slice().reverse().slice(0,10).map(r=><div className="cot-row" key={r.date}><span>{r.date}</span><span>{fmt(r.nonCommercialLong)}</span><span>{fmt(r.nonCommercialShort)}</span><strong className={r.nonCommercialNet>=0?'positive':'negative'}>{fmt(r.nonCommercialNet)}</strong></div>)}</div></div>
  <div className="research-disclaimer"><strong>Methodology note.</strong> COT is a weekly positioning snapshot and is not a real-time trading signal. Position data should be interpreted with price structure, macro conditions and the report's publication lag in mind.</div>
 </section></main>
}
